from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import train_test_split


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DATASET_PATH = PROJECT_ROOT / "data" / "ai4i2020.csv"
OUTPUT_PATH = PROJECT_ROOT / "backend" / "src" / "model" / "anomalyModel.json"

FEATURE_COLUMNS = [
    "Air temperature [K]",
    "Process temperature [K]",
    "Rotational speed [rpm]",
    "Torque [Nm]",
    "Tool wear [min]",
]
TARGET_COLUMN = "Machine failure"

FEATURE_NAMES = {
    "Air temperature [K]": "airTemperatureK",
    "Process temperature [K]": "processTemperatureK",
    "Rotational speed [rpm]": "rotationalSpeedRpm",
    "Torque [Nm]": "torqueNm",
    "Tool wear [min]": "toolWearMin",
}


def load_dataset() -> pd.DataFrame:
    return pd.read_csv(DATASET_PATH, encoding="utf-8-sig")


def build_feature_statistics(features: pd.DataFrame) -> dict[str, dict[str, float]]:
    statistics: dict[str, dict[str, float]] = {}

    for column in FEATURE_COLUMNS:
        series = features[column]
        statistics[FEATURE_NAMES[column]] = {
            "mean": round(float(series.mean()), 4),
            "std": round(float(series.std()), 4),
            "min": round(float(series.min()), 4),
            "max": round(float(series.max()), 4),
        }

    return statistics


def build_scoring_parameters(
    statistics: dict[str, dict[str, float]],
    feature_importance: dict[str, float],
) -> dict[str, Any]:

    return {
        "anomalyScoreThreshold": 50,
        "healthScoreFormula": "100 - anomalyScore",
        "zScoreWarningThreshold": 2,
        "zScoreCriticalThreshold": 3,
        "recommendedFeatureWeights": feature_importance,
        "featureRanges": {
            feature: {
                "low": values["mean"] - values["std"],
                "high": values["mean"] + values["std"],
            }
            for feature, values in statistics.items()
        },
    }


def train_model() -> dict[str, Any]:
    dataset = load_dataset()
    features = dataset[FEATURE_COLUMNS]
    target = dataset[TARGET_COLUMN]

    x_train, x_test, y_train, y_test = train_test_split(
        features,
        target,
        test_size=0.2,
        random_state=42,
        stratify=target,
    )

    model = RandomForestClassifier(
        n_estimators=100,
        random_state=42,
        class_weight="balanced",
    )
    model.fit(x_train, y_train)

    predictions = model.predict(x_test)
    statistics = build_feature_statistics(features)
    feature_importance = {
        FEATURE_NAMES[column]: round(float(importance), 6)
        for column, importance in zip(FEATURE_COLUMNS, model.feature_importances_)
    }

    return {
        "metadata": {
            "modelType": "RandomForestClassifier",
            "trainingMode": "offline",
            "dataset": "AI4I 2020 Predictive Maintenance Dataset",
            "target": TARGET_COLUMN,
            "rowCount": int(len(dataset)),
            "featureColumns": [FEATURE_NAMES[column] for column in FEATURE_COLUMNS],
            "notes": (
                "Generated by ml/train_model.py. The Node.js backend should read "
                "this JSON as exported model statistics, not run Python at request time."
            ),
        },
        "metrics": {
            "accuracy": round(float(accuracy_score(y_test, predictions)), 4),
            "classificationReport": classification_report(
                y_test,
                predictions,
                output_dict=True,
                zero_division=0,
            ),
        },
        "featureStatistics": statistics,
        "featureImportance": feature_importance,
        "scoringParameters": build_scoring_parameters(
            statistics,
            feature_importance,
        ),
    }


def main() -> None:
    export_data = train_model()
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(
        json.dumps(export_data, indent=4),
        encoding="utf-8",
    )
    print(f"Exported model statistics to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()

